# -*- mode: ruby -*-
# vi: set ft=ruby :

# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.
#

$LOAD_PATH.unshift File.dirname(__FILE__)

require "master.rb"
require "node.rb"
require "rhost.rb"

nodesCount = Integer(ENV['KD_NODES_COUNT'] || '1')
rhostsCount = Integer(ENV['KD_RHOSTS_COUNT'] || '0')

# Please set valid IPs/credentials/data for you infrastructure. Otherwise
# many things will not work (incl. deploy, unittests, integration tests etc.)
$oneUsername = ENV['KD_ONE_USERNAME'] || ''
$onePassword = ENV['KD_ONE_PASSWORD'] || ''
$oneURL      = ENV['KD_ONE_URL'] || 'https://some.nebula.host.com:2633/RPC2'
privateKey  = ENV['KD_ONE_PRIVATE_KEY'] || '~/.ssh/id_rsa'

oneTemplateName = ENV['KD_NEBULA_TEMPLATE'] || 'kd-dev-public-net'
oneTemplateId = Integer(ENV['KD_NEBULA_TEMPLATE_ID'] || 0)


Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.2"

  config.ssh.username = 'root'
  config.ssh.insert_key = 'true'

  #Disable default sync folder
  config.vm.synced_folder ".", "/vagrant", disabled: true

  rsyncExcludes = [".git/", ".venv/", "ceph_settings.py", ".license"]

  gitignoreFile = File.expand_path("../../../.gitignore", __FILE__)
  if File.readable?(gitignoreFile)
    File.open(gitignoreFile) do |f|
      f.each_line do |line|
        line.chomp!
        next if line.empty?
        # FIXME: I've spent hours to figure out how and why excluding
        # exactly this one line fixes rsync'ing of "updates/scripts/" folder
        # but can't find any reason. This small extra folder doesn't add any
        # noticeable overhead, so this "fix" is acceptable for now
        next if line == ".idea"
        rsyncExcludes << line
      end
    end
  end

  config.vm.provider "virtualbox" do |vb, override|
    override.ssh.password = 'vagrant'
    vb.linked_clone = true if Vagrant::VERSION =~ /^1.[8-9]/
  end

  config.vm.provider :opennebula do |one, override|
    one.endpoint = $oneURL
    one.username = $oneUsername
    one.password = $onePassword
    if oneTemplateId > 0
      one.template_id = oneTemplateId
    else
      one.template_name = oneTemplateName
    end

    override.ssh.private_key_path = privateKey
  end

  if nodesCount > 0
      (1..nodesCount).each do |i|
          config.vm.define "kd_node#{i}" do |node|
              config_node(node, i)
          end
      end
  end

  if rhostsCount > 0
      (1..rhostsCount).each do |i|
          config.vm.define "kd_rhost#{i}" do |rhost|
              config_rhost(rhost, i, nodesCount)
          end
      end
  end

  config.vm.define "kd_master" do |master|
      if ARGV[0] == "gatling-rsync-auto" || ARGV[0] == "rsync-auto"
          master.vm.synced_folder "../../", "/var/opt/kuberdock", type: "rsync", rsync__exclude: rsyncExcludes
          master.gatling.rsync_on_startup = false
      end
      config_master(master, nodesCount, rhostsCount)
  end
end
