# -*- mode: ruby -*-
# vi: set ft=ruby :
#
#
#
#
nodesCount = Integer(ENV['KD_NODES_COUNT'] || '1')

masterMemory = Integer(ENV['KD_MASTER_MEMORY'] || '1024')
masterCpus = Integer(ENV['KD_MASTER_CPUS'] || '1')

nodeMemory = Integer(ENV['KD_NODE_MEMORY'] || '2048')
nodeCpus = Integer(ENV['KD_NODE_CPUS'] || '2')

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.synced_folder "../../", "/vagrant"
  config.ssh.username = 'root'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = 'true'

  # AC-2890 Multinodes

  (1..nodesCount).each do |i|
      config.vm.define "kd_node#{i}" do |node|
          node.vm.hostname = "node#{i}"
          node.vm.network "private_network", ip: "192.168.77.#{20+i}", virtualbox__intnet: true
          node.vm.provider "virtualbox" do |vb|
            vb.memory = nodeMemory
            vb.cpus = nodeCpus
          end
      end
  end

  config.vm.define "kd_master" do |master|
      master.vm.hostname = "master"
      master.vm.network "private_network", ip: "192.168.77.20", virtualbox__intnet: true
      master.vm.network "forwarded_port", guest: 5000, host: 5000
      master.vm.provider "virtualbox" do |vb|
        vb.memory = masterMemory
        vb.cpus = masterCpus
      end
      master.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/main.yml"
        ansible.limit = 'all'
        ansible.groups = {
            "master" => ["kd_master"],
            "node" => ["kd_node[1:#{nodesCount}]"],
        }
      end
  end

  # config.vbguest.auto_update = false
  # config.vm.box_check_update = false
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  #
  #
end
