FROM centos:7

RUN yum -y install epel-release && \
    yum -y update && \
    yum -y install rsync rpm-build gcc nodejs nodejs-less nodejs-clean-css && \
    yum clean all

# Rebuild & push with:
# docker build -t lobur/rpm-build:vX -f dev-utils/Dockerfile.rpm-build --rm=true --no-cache=true --pull .
# docker push lobur/rpm-build:vX

# Always bump X, this is
# needed to make sure the new image gets pulled on Jenkins
# If you are not lobur use your own hub.docker.com account
