FROM centos:6

RUN yum -y install epel-release && \
    yum -y update && \
    yum -y install python-pip && \
    yum clean all
RUN pip install --upgrade pip && pip install virtualenv

# Pre-build test env. Before test run requirements are checked again.
# It is much faster to check/install-missing than full install.
COPY requirements-dev.txt /

RUN cd / && \
    virtualenv venv && \
    source venv/bin/activate && \
    pip install -r requirements-dev.txt && \
    rm -f requirements-dev.txt

# Rebuild & push with (always bump X):
# docker build -t USER/centos6-test-base:vX -f Dockerfile.centos6-test-base --rm=true --no-cache=true --pull .
# docker push USER/centos6-test-base:vX
