FROM centos:7

RUN yum -y install epel-release && \
    yum -y update && \
    yum -y install python-pip python-devel postgresql-contrib postgresql-devel gcc nmap && \
    yum clean all
RUN pip install --upgrade pip && pip install virtualenv

# Pre-build test env. Before test run requirements are checked again.
# It is much faster to check/install-missing than full install.
COPY requirements.txt requirements-dev.txt /

# FIXME http://stackoverflow.com/questions/38836293/make-python-libraries-installed-with-requirements-txt-immediately-available
RUN cd / && \
    virtualenv venv && \
    source venv/bin/activate && \
    pip install requests==2.4.3 && \
    pip install -r requirements.txt -r requirements-dev.txt && \
    rm -f requirements.txt requirements-dev.txt

# Rebuild & push with (always bump X):
# docker build -t lobur/centos7-test-base:vX -f Dockerfile.centos7-test-base --rm=true --no-cache=true --pull .
# docker push lobur/centos7-test-base:vX

# Always bump X, including Dockerfile.test, this is
# needed to make sure the new image gets pulled on Jenkins
# If you are not lobur use your own hub.docker.com account
