"""add_pod_template_id_column

Revision ID: 1139a080f512
Revises: 312700b6c892
Create Date: 2015-09-25 15:39:43.426778

"""

# revision identifiers, used by Alembic.
revision = '1139a080f512'
down_revision = '312700b6c892'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pods', sa.Column('template_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pods', 'template_id')
    ### end Alembic commands ###
