"""Add localstorage_devices table

Revision ID: 1a24688cc541
Revises: 3dc83a81f385
Create Date: 2016-06-22 08:36:11.498368

"""

# revision identifiers, used by Alembic.
revision = '1a24688cc541'
down_revision = '3dc83a81f385'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localstorage_devices',
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('device', sa.String(length=64), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('volume_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], [u'nodes.id'], ),
    sa.PrimaryKeyConstraint('node_id', 'device')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('localstorage_devices')
    ### end Alembic commands ###
