"""add image field to PA

Revision ID: 1f26cf5abc0f
Revises: 11bf9b6a89b2
Create Date: 2016-11-22 11:01:25.196844

"""

# revision identifiers, used by Alembic.
revision = '1f26cf5abc0f'
down_revision = '11bf9b6a89b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predefined_apps', sa.Column('icon', sa.Text(),
                                               nullable=True))
    op.add_column('predefined_apps', sa.Column('search_available', sa.Boolean(),
                                               default=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predefined_apps', 'icon')
    op.drop_column('predefined_apps', 'search_available')
    ### end Alembic commands ###
