
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.

"""add image field to PA

Revision ID: 1f26cf5abc0f
Revises: 11bf9b6a89b2
Create Date: 2016-11-22 11:01:25.196844

"""

# revision identifiers, used by Alembic.
revision = '1f26cf5abc0f'
down_revision = '11bf9b6a89b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predefined_apps', sa.Column('icon', sa.Text(),
                                               nullable=True))
    op.add_column('predefined_apps', sa.Column('search_available', sa.Boolean(),
                                               default=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predefined_apps', 'icon')
    op.drop_column('predefined_apps', 'search_available')
    ### end Alembic commands ###
