
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.

"""Add state field to persistent disk records

Revision ID: 27ac98113841
Revises: 4078673e3670
Create Date: 2016-01-13 17:03:19.797906

"""

# revision identifiers, used by Alembic.
revision = '27ac98113841'
down_revision = '4078673e3670'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'persistent_disk',
        sa.Column('state', sa.Integer(), nullable=False, server_default='0')
    )
    conn = op.get_bind()
    conn.execute("UPDATE persistent_disk SET state=0")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persistent_disk', 'state')
    ### end Alembic commands ###
