"""Add state field to persistent disk records

Revision ID: 27ac98113841
Revises: 4078673e3670
Create Date: 2016-01-13 17:03:19.797906

"""

# revision identifiers, used by Alembic.
revision = '27ac98113841'
down_revision = '4078673e3670'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'persistent_disk',
        sa.Column('state', sa.Integer(), nullable=False, server_default='0')
    )
    conn = op.get_bind()
    conn.execute("UPDATE persistent_disk SET state=0")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persistent_disk', 'state')
    ### end Alembic commands ###
