
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.

"""Add relation between Node and IPPool

Revision ID: 3dc83a81f385
Revises: 30ad174aa45a
Create Date: 2016-06-07 09:40:05.047326

"""

# revision identifiers, used by Alembic.
revision = '3dc83a81f385'
down_revision = '3c832810a33c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ippool', sa.Column('node_id', sa.Integer(), nullable=True))
    op.create_foreign_key(u'ippool_node_id_fkey', 'ippool', 'nodes', ['node_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'ippool_node_id_fkey', 'ippool', type_='foreignkey')
    op.drop_column('ippool', 'node_id')
    ### end Alembic commands ###
