"""Add node flags table

Revision ID: 3505518f6f4f
Revises: 79a6e3998d6
Create Date: 2015-10-29 18:03:45.928635

"""

# revision identifiers, used by Alembic.
revision = '3505518f6f4f'
down_revision = '79a6e3998d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('flag_name', sa.String(length=63), nullable=False),
    sa.Column('flag_value', sa.String(length=127), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], [u'nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deleted_node_id_flag_name', 'node_flags', ['deleted', 'node_id', 'flag_name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deleted_node_id_flag_name', table_name='node_flags')
    op.drop_table('node_flags')
    ### end Alembic commands ###
