"""Add predefined_apps table

Revision ID: 382d3b1e63aa
Revises: 53489a9c1e2d
Create Date: 2015-09-08 10:53:16.669877

"""

# revision identifiers, used by Alembic.
revision = '382d3b1e63aa'
down_revision = '53489a9c1e2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'predefined_apps',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('template', sa.Text(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predefined_apps')
    ### end Alembic commands ###
