"""add versions to predefined_applications

Revision ID: 3e7a44cbe1e2
Revises: 8d3aed3e74c
Create Date: 2016-09-08 13:30:48.254760

"""

# revision identifiers, used by Alembic.
revision = '3e7a44cbe1e2'
down_revision = '8d3aed3e74c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

Session = sessionmaker()
Base = declarative_base()


class PredefinedApp(Base):
    __tablename__ = 'predefined_apps'

    id = sa.Column(sa.Integer, primary_key=True, autoincrement=True,
                   nullable=False)
    template = sa.Column(sa.Text, nullable=False)
    created = sa.Column(sa.DateTime, nullable=True)
    modified = sa.Column(sa.DateTime, nullable=True)


class PredefinedAppTemplate(Base):
    __tablename__ = 'predefined_app_templates'

    id = sa.Column(sa.Integer, primary_key=True, autoincrement=True,
                   nullable=False)
    predefined_app_id = sa.Column(sa.Integer,
                                  sa.ForeignKey("predefined_apps.id"),
                                  nullable=False)
    template = sa.Column(sa.Text, nullable=False)
    active = sa.Column(sa.Boolean, default=False, nullable=False)
    switching_allowed = sa.Column(sa.Boolean, default=False, nullable=False)
    is_deleted = sa.Column(sa.Boolean, default=False, nullable=False)
    created = sa.Column(sa.DateTime, nullable=True)
    modified = sa.Column(sa.DateTime, nullable=True)

    __table_args__ = (
        sa.Index('predefined_app_id_active', 'predefined_app_id', 'active',
                 unique=True, postgresql_where=active),
        sa.CheckConstraint('NOT (active AND is_deleted)'),
    )


def upgrade_data(bind):
    session = Session(bind=bind)
    q = session.query(PredefinedApp)
    for item in q:
        tpl = PredefinedAppTemplate(predefined_app_id=item.id,
                                    template=item.template,
                                    created=item.created,
                                    modified=item.modified,
                                    active=True,
                                    switching_allowed=True)
        session.add(tpl)
    session.commit()


def upgrade():
    bind = op.get_bind()
    PredefinedAppTemplate.__table__.create(bind)

    upgrade_data(bind)

    op.drop_column(u'predefined_apps', 'template')
    op.add_column(u'predefined_apps', sa.Column('is_deleted',
                                                sa.Boolean,
                                                server_default='False',
                                                nullable=False)
                  )


def downgrade_data(bind):
    session = Session(bind=bind)
    q = session.query(PredefinedAppTemplate).filter(
        PredefinedAppTemplate.active.is_(True))
    for item in q:
        pa = session.query(PredefinedApp).filter(
            PredefinedApp.id == item.predefined_app_id).first()
        pa.template = item.template
    session.commit()


def downgrade():
    bind = op.get_bind()
    Base.metadata.bind = bind
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'predefined_apps', sa.Column('template', sa.TEXT(),
                                                nullable=True))
    op.drop_column(u'predefined_apps', 'is_deleted')

    downgrade_data(bind)

    op.alter_column(u'predefined_apps', u'template', nullable=False)

    op.drop_table('predefined_app_templates')
    ### end Alembic commands ###
