"""Rename kubes field from total_traffic to included_traffic

Revision ID: 3f771e33622a
Revises: 144bf08f16b
Create Date: 2015-09-07 03:42:50.032076

"""

# revision identifiers, used by Alembic.
revision = '3f771e33622a'
down_revision = '144bf08f16b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kubes', sa.Column('included_traffic', sa.Integer(), server_default='0', nullable=False))
    conn = op.get_bind()
    conn.execute("UPDATE kubes SET included_traffic=total_traffic")
    op.drop_column('kubes', 'total_traffic')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kubes', sa.Column('total_traffic', sa.INTEGER(), autoincrement=False,
                                     server_default='0', nullable=False))
    conn = op.get_bind()
    conn.execute("UPDATE kubes SET total_traffic=included_traffic")
    op.drop_column('kubes', 'included_traffic')
    ### end Alembic commands ###
