
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.

"""Rename kubes field from total_traffic to included_traffic

Revision ID: 3f771e33622a
Revises: 144bf08f16b
Create Date: 2015-09-07 03:42:50.032076

"""

# revision identifiers, used by Alembic.
revision = '3f771e33622a'
down_revision = '144bf08f16b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kubes', sa.Column('included_traffic', sa.Integer(), server_default='0', nullable=False))
    conn = op.get_bind()
    conn.execute("UPDATE kubes SET included_traffic=total_traffic")
    op.drop_column('kubes', 'total_traffic')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kubes', sa.Column('total_traffic', sa.INTEGER(), autoincrement=False,
                                     server_default='0', nullable=False))
    conn = op.get_bind()
    conn.execute("UPDATE kubes SET total_traffic=included_traffic")
    op.drop_column('kubes', 'included_traffic')
    ### end Alembic commands ###
