
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.

"""Add optional node binding to persistent disk structure

Revision ID: 4ded025d2f29
Revises: 2df8c40ab250
Create Date: 2016-02-22 10:41:15.908527

"""

# revision identifiers, used by Alembic.
revision = '4ded025d2f29'
down_revision = '2df8c40ab250'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_disk', sa.Column('node_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'persistent_disk', 'nodes', ['node_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persistent_disk', type_='foreignkey')
    op.drop_column('persistent_disk', 'node_id')
    ### end Alembic commands ###
