"""Add optional node binding to persistent disk structure

Revision ID: 4ded025d2f29
Revises: 2df8c40ab250
Create Date: 2016-02-22 10:41:15.908527

"""

# revision identifiers, used by Alembic.
revision = '4ded025d2f29'
down_revision = '2df8c40ab250'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persistent_disk', sa.Column('node_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'persistent_disk', 'nodes', ['node_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persistent_disk', type_='foreignkey')
    op.drop_column('persistent_disk', 'node_id')
    ### end Alembic commands ###
