"""Add certificate to BaseDomain model

Revision ID: 50451812ee04
Revises: 3e7a44cbe1e2
Create Date: 2016-12-01 18:29:52.961664

"""

# revision identifiers, used by Alembic.
revision = '50451812ee04'
down_revision = '3e7a44cbe1e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_domains', sa.Column('certificate_cert', sa.String(length=8192), nullable=True))
    op.add_column('base_domains', sa.Column('certificate_key', sa.String(length=8192), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_domains', 'certificate_key')
    op.drop_column('base_domains', 'certificate_cert')
    ### end Alembic commands ###
