
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.

"""Add certificate to BaseDomain model

Revision ID: 50451812ee04
Revises: 3e7a44cbe1e2
Create Date: 2016-12-01 18:29:52.961664

"""

# revision identifiers, used by Alembic.
revision = '50451812ee04'
down_revision = '3e7a44cbe1e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_domains', sa.Column('certificate_cert', sa.String(length=8192), nullable=True))
    op.add_column('base_domains', sa.Column('certificate_key', sa.String(length=8192), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_domains', 'certificate_key')
    op.drop_column('base_domains', 'certificate_cert')
    ### end Alembic commands ###
