
# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.

"""add_timestamps_to_predefined_apps

Revision ID: 5049471549ba
Revises: 33ae2dd8e49b
Create Date: 2015-11-06 10:45:45.942870

"""

# revision identifiers, used by Alembic.
revision = '5049471549ba'
down_revision = '33ae2dd8e49b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predefined_apps', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('predefined_apps', sa.Column('modified', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predefined_apps', 'modified')
    op.drop_column('predefined_apps', 'created')
    ### end Alembic commands ###
