"""add_timestamps_to_predefined_apps

Revision ID: 5049471549ba
Revises: 33ae2dd8e49b
Create Date: 2015-11-06 10:45:45.942870

"""

# revision identifiers, used by Alembic.
revision = '5049471549ba'
down_revision = '33ae2dd8e49b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predefined_apps', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('predefined_apps', sa.Column('modified', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predefined_apps', 'modified')
    op.drop_column('predefined_apps', 'created')
    ### end Alembic commands ###
