"""Add system_settings table

Revision ID: 589e137e4b7c
Revises: 33b1e3a97fb8
Create Date: 2015-10-14 11:12:58.242206

"""

# revision identifiers, used by Alembic.
revision = '589e137e4b7c'
down_revision = '33b1e3a97fb8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deleted_name', 'system_settings', ['deleted', 'name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    ### end Alembic commands ###
