"""Add pod states table

Revision ID: 79a6e3998d6
Revises: 3a8320be841c
Create Date: 2015-10-21 10:14:57.865340

"""

# revision identifiers, used by Alembic.
revision = '79a6e3998d6'
down_revision = '3a8320be841c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pod_states',
    sa.Column('pod_id', postgresql.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('last_event_time', sa.DateTime(), nullable=True),
    sa.Column('last_event', sa.String(length=255), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ),
    sa.PrimaryKeyConstraint('pod_id', 'start_time')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pod_states')
    ### end Alembic commands ###
