"""Add RegisteredHost.tunnel_ip column

Revision ID: 81398dd39d6
Revises: 3149fa6dc22b
Create Date: 2016-11-08 19:04:16.499087

"""

# revision identifiers, used by Alembic.
revision = '81398dd39d6'
down_revision = '3149fa6dc22b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registered_hosts', sa.Column('tunnel_ip', sa.String(),
                                                nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registered_hosts', 'tunnel_ip')
    ### end Alembic commands ###
