#!/usr/bin/python

import argparse

from kubecli.container.kubectl import parser as kubectl
from kubecli.container.kuberdock import parser as kuberdock
from kubecli.image.docker import parser as docker


def process_args():
    parser = argparse.ArgumentParser("KuberDock command line utilities")
    parser.add_argument('-c', '--config', default='~/.kubecli.conf')
    parser.add_argument(
        '-j', '--json', action="store_true", help="Output data as JSON")
    parser.add_argument('-d', '--debug', action="store_true", help="Turn on curl logging")

    subs = parser.add_subparsers(
        help="Commands",
        title="Commands",
        description="Valid commands",
        dest="target")

    kubectl(subs)
    kuberdock(subs)
    docker(subs)
    return parser.parse_args()


if __name__ == '__main__':
    args = process_args()
    args.call(args)
