#!/usr/bin/python

# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.


import argparse

from kubecli.container.kubectl import parser as kubectl
from kubecli.container.kuberdock import parser as kuberdock
from kubecli.image.docker import parser as docker


def process_args():
    parser = argparse.ArgumentParser("KuberDock command line utilities")
    parser.add_argument('-c', '--config', default='~/.kubecli.conf')
    parser.add_argument(
        '-j', '--json', action="store_true", help="Output data as JSON")
    parser.add_argument('-d', '--debug', action="store_true",
                        help="Log all HTTP requests as cURL")
    parser.add_argument('-k', '--no-http-warnings', action="store_true",
                        help='Disable HTTP warnings')

    subs = parser.add_subparsers(
        help="Commands",
        title="Commands",
        description="Valid commands",
        dest="target")

    kubectl(subs)
    kuberdock(subs)
    docker(subs)
    return parser.parse_args()


def _disable_requests_warnings():
    import requests
    requests.packages.urllib3.disable_warnings()


if __name__ == '__main__':
    args = process_args()

    if args.no_http_warnings:
        _disable_requests_warnings()

    args.call(args)
