#!/usr/bin/env python2

# KuberDock - is a platform that allows users to run applications using Docker
# container images and create SaaS / PaaS based on these applications.
# Copyright (C) 2017 Cloud Linux INC
#
# This file is part of KuberDock.
#
# KuberDock is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# KuberDock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KuberDock; if not, see <http://www.gnu.org/licenses/>.

"""
This script will be called from cron so error handling is pretty trivial,
because we can't do anything with errors here
"""

import subprocess

UNAME_LEN = 30
USERS_HOME = '/var/lib/kuberdock/kd-ssh-users-home'

# If any error, we let it fail because we can't do anything here
running = subprocess.check_output(['docker', 'ps', '--format', '{{.ID}}',
                                   '--no-trunc=true']).split()
running = map(lambda x: x[:UNAME_LEN], running)

with open('/etc/passwd') as f:
    for line in f:
        user = line.split(':')[0]
        if (USERS_HOME not in line) or (len(user) != UNAME_LEN):
            continue
        if user not in running:
            try:
                subprocess.check_call(['userdel', '-rf', user])
            except subprocess.CalledProcessError:
                pass
