#!/usr/bin/env python

from __future__ import print_function

if __name__ == '__main__':
    import requests

    import logging
    logging.basicConfig(format='%(message)s')

    requests.packages.urllib3.disable_warnings(
        requests.packages.urllib3.exceptions.InsecureRequestWarning
    )

    from kdctllib.parser.main import main
    from kdctllib.parser import ippool
    from kdctllib.parser import nodes
    from kdctllib.parser import predefined_apps
    from kdctllib.parser import restore
    from kdctllib.parser import system_settings
    from kdctllib.parser import users

    from kdctllib.parser import utils

    try:
        print(main())
    except Exception as e:
        raise SystemExit(utils.formatted(e.message))
