#!/usr/bin/env python

from __future__ import print_function

if __name__ == '__main__':
    import logging

    logging.basicConfig(format='%(message)s')

    from kdctllib.cli import access, settings, initialize
    initialize(access.ADMIN, settings.KDCtlSettings)

    from kdctllib.cli.main import main
    main()
